### ISSUE TITLE
Enable Partners section

### ISSUE THREAD

**Issue by luixaviles** [luixaviles/ng-bolivia-website#26]
Enable "Partners" section with the name "Community Partners".

- Reference: [https://hoverboard-dev.firebaseapp.com/](https://hoverboard-dev.firebaseapp.com/) 
- Logos and Resources here: [https://drive.google.com/drive/folders/1i01pUtKypBFC_5Ion0QhtS6xP-uq86Cn?usp=sharing](https://drive.google.com/drive/folders/1i01pUtKypBFC_5Ion0QhtS6xP-uq86Cn?usp=sharing)
- Review document on shared folder to have right names and links for all communities.

**Comment by diegosebgonz** [comment]
Sent to CR.

**Comment by diegosebgonz** [comment]
Close!
